export enum NEW_AUTH_ERRORS {
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
  PHONE_NUMBER_ALREADY_USED = 'PHONE_NUMBER_ALREADY_USED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_PASSWORD_PATTERN = 'INVALID PATTERN. PASSWORD MUST HAS AT LEAST 10 SYMBOLS: AT LEAST 8 LETTERS (UPPER AND LOWER CASE), ONE NUMBER, AND ONE SPECIAL CHARACTER (!@#$%^&*()_+=).',
  ACCESS_TOKEN_NOT_FOUND = 'ACCESS_TOKEN_NOT_FOUND',
  ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_NOT_PROVIDED = 'REFRESH_TOKEN_NOT_PROVIDED',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
}
